import test from 'node:test';import assert from 'node:assert/strict';import {updateAlert,humanMessage} from '../notifications/alerts.js';import {alertsHandler} from '../services/alerts.js';import {MemoryStore} from '../state/store.js';import {health} from '../services/health.js';
const now=Date.UTC(2026,8,14),none={macro:'NEUTRAL',side:'NONE',entry:null,stop_loss:null,take_profit:null},sell={macro:'BEARISH',side:'SELL',entry:4289.4,stop_loss:4293.1,take_profit:4281.6};
const fields=['macro','side','entry','stop_loss','take_profit','human_message','updated_at','signal_id'];
const res=()=>({setHeader(){},status(x){this.code=x;return this;},json(x){this.body=x;return this;}});
async function repo(state){const r=new MemoryStore();r.durable=true;await r.compareAndSet(null,JSON.stringify(state));return r;}
test('initial NONE stored once; all fields/hash/time immutable on identical calls',()=>{const s={};assert.equal(updateAlert(s,none,now),true);const before=structuredClone(s);assert.equal(updateAlert(s,none,now+60000),false);assert.deepEqual(s,before);assert.deepEqual(Object.keys(s.latest_alert),fields);assert.equal(s.latest_alert.human_message,'宏观：中性\n本单：无交易');});
test('fixed short/long template and unique signal metadata',()=>{const s={candidate:{id:'one'}};updateAlert(s,sell,now);assert.equal(s.latest_alert.signal_id,'one');assert.equal(s.latest_alert.human_message,'宏观：偏空\n本单：空\n入场：4289.40\n止损：4293.10\n止盈：4281.60');assert.ok(humanMessage({...sell,macro:'BULLISH',side:'BUY'}).startsWith('宏观：偏多\n本单：多'));});
test('side, SL, TP and pre-active entry changes each update exactly once',()=>{const s={};updateAlert(s,none,now);for(const [i,c] of [sell,{...sell,stop_loss:4292},{...sell,stop_loss:4292,take_profit:4282},{...sell,entry:4289},none].entries()){assert.equal(updateAlert(s,c,now+(i+1)*60000),true);const original=structuredClone(s);assert.equal(updateAlert(s,c,now+(i+1)*60000+1),false);assert.deepEqual(s,original);}});
test('macro-only change without permission impact leaves stored alert and hash unchanged',()=>{const s={};updateAlert(s,sell,now);const before=structuredClone(s);assert.equal(updateAlert(s,{...sell,macro:'NEUTRAL'},now+60000),false);assert.deepEqual(s,before);});
test('ACTIVE prevents entry changes; permission cancellation still updates',()=>{const s={active_signal:{status:'ACTIVE',signal_id:'one',entry:sell.entry}};updateAlert(s,sell,now);assert.equal(updateAlert(s,{...sell,entry:5000},now+1),false);assert.equal(updateAlert(s,none,now+2),true);assert.equal(s.latest_alert.entry,null);});
test('legacy alert migration removes old dispatch state without new timestamp',()=>{const s={latest_alert:{contract:sell,created_at:now,signal_id:'one',email_status:'PENDING'},email_outbox:[{}],last_alert_contract_hash:'old'};assert.equal(updateAlert(s,sell,now+60000),false);assert.deepEqual(Object.keys(s.latest_alert),fields);assert.equal(s.alert_updated_at,new Date(now).toISOString());assert.equal('email_outbox' in s,false);assert.equal('last_alert_contract_hash' in s,false);});
test('fresh endpoint has exactly eight fields and performs no write',async()=>{const s={last_watch:{at:new Date(now).toISOString()}};updateAlert(s,sell,now);const r=await repo(s),before=await r.read(),out=res();await alertsHandler({repository:r,now:()=>now+1000})({method:'GET'},out);assert.equal(out.code,200);assert.deepEqual(Object.keys(out.body),fields);assert.deepEqual(out.body,s.latest_alert);assert.equal(await r.read(),before);});
test('stale/missing/future watcher returns same shape with NONE',async()=>{for(const t of [now-120001,now+1,null]){const s={last_watch:t===null?null:{at:new Date(t).toISOString()}};updateAlert(s,sell,now-1000);const out=res();await alertsHandler({repository:await repo(s),now:()=>now})({method:'GET'},out);assert.equal(out.code,503);assert.deepEqual(Object.keys(out.body),fields);assert.equal(out.body.side,'NONE');assert.equal(out.body.entry,null);assert.equal(out.body.updated_at,new Date(now-1000).toISOString());}});
test('store errors and invalid methods retain exact safe response shape',async()=>{for(const method of ['GET','POST']){const out=res();await alertsHandler({repository:{durable:true,read:async()=>{throw Error('secret');}}})({method},out);assert.deepEqual(Object.keys(out.body),fields);assert.equal(out.body.side,'NONE');assert.ok(!JSON.stringify(out.body).includes('secret'));}});
test('health contains latest alert time and no removed configuration',async()=>{const s={revision:1,last_watch:{at:new Date(now).toISOString()},alert_updated_at:new Date(now-1000).toISOString()};const x=await health({repository:await repo(s),now,fetcher:async()=>{throw Error();}});assert.equal(x.latest_alert_time,s.alert_updated_at);assert.equal(x.watcher_recent,true);assert.equal(Object.keys(x).some(k=>/email|resend/i.test(k)),false);});
