import test from 'node:test';import assert from 'node:assert/strict';
import {timing,missed} from '../engine/timeliness.js';import {stateKey,MemoryStore} from '../state/store.js';import {health} from '../services/health.js';
const input={now:100,quote:{price:100,fresh:true}};
const result=()=>({key_levels:[{price:101,available_at:99}],reason:[],action:'NO_TRADE'});
test('prepare never authorizes entry; stale quote never prepares',()=>{let r=result();timing({},r,input);assert.equal(r.stage,'PREPARE');assert.equal(r.action,'OBSERVE');r=result();timing({},r,{...input,quote:{price:100,fresh:false}});assert.equal(r.action,'NO_TRADE');});
test('armed provisional extreme is not moved to satisfy risk and cannot execute',()=>{const state={candidate:{stage:'RECLAIM',direction:'BUY',extreme:90,trigger:100}};const r=result();timing(state,r,input);assert.equal(r.stage,'ARMED');assert.equal(r.stop_loss,89.99);assert.equal(r.action,'OBSERVE');assert.equal(r.provisional_plan.basis,'PROVISIONAL_EXTREME_PENDING_FIRST_RETEST');});
test('missed distance is directional; missed setup cannot revive on return',()=>{const c={direction:'BUY',trigger:100,retest:{close:101},stage:'SIGNAL_READY'};assert.equal(missed(c,103),false);assert.equal(missed(c,103.01),true);assert.equal(missed(c,98),false);c.timing_missed=true;const r=result();timing({candidate:c},r,input);assert.equal(r.stage,'MISSED');assert.equal(r.action,'NO_TRADE');});
test('preview branch state never collides with production or another preview branch',()=>{const a=stateKey({VERCEL_ENV:'preview',VERCEL_GIT_COMMIT_REF:'a'});assert.notEqual(a,stateKey({VERCEL_ENV:'production'}));assert.notEqual(a,stateKey({VERCEL_ENV:'preview',VERCEL_GIT_COMMIT_REF:'b'}));});
test('health redacts failures and does not claim memory store persistence',async()=>{const x=await health({repository:new MemoryStore(),fetcher:async()=>{throw Error('SECRET')}});assert.equal(x.app_ok,true);assert.equal(x.redis_ok,false);assert.equal(x.state_storage_ok,false);assert.equal(x.action,'NO_TRADE');assert.ok(!JSON.stringify(x).includes('SECRET'));});
