import test from 'node:test';import assert from 'node:assert/strict';
import {manageActive} from '../engine/active.js';import {macroFilter} from '../engine/macroFilter.js';import {humanMessage,updateAlert} from '../notifications/alerts.js';import {MemoryStore} from '../state/store.js';import {executionDecision} from '../engine/execution.js';
const base=Date.UTC(2026,0,1),M=300000;
function f(){const now=base+10*M,rows=Array.from({length:10},(_,i)=>({at:base+i*M,end:base+(i+1)*M,open:102,high:103,low:101,close:102}));return {state:{candidate:{id:'one',direction:'BUY'},active_signal:{signal_id:'one',status:'ACTIVE',side:'BUY',entry:100,initial_stop_loss:98,initial_take_profit:110,activated_at:base,stop_loss:98,take_profit:110,initial_risk:2,last_quote_at:base,last_structure_at:base,management_events:[]}},input:{now,quote:{price:103,at:now,fresh:true},dxy:{provider:'ITICK',valid:true,fresh:true,timestamp:new Date(now).toISOString(),at:now,available_at:now,move_5m_pct:-.1,move_15m_pct:-.2},calendar:{ok:true,data:[]},m5:{valid:rows,quality:'GOOD'},m15:{quality:'GOOD'}},result:{data_quality:{state_durable:true,confirmation_fresh:true},key_levels:[]},decision:{contract:{macro:'BULLISH',side:'SELL',entry:200,stop_loss:201,take_profit:190}}};}
const run=x=>manageActive(x.state,x.input,x.result,x.decision);
for(const [m15,m5,bias] of [[.10,-.03,'BEARISH'],[-.10,.03,'BULLISH'],[.10,-.03001,'NEUTRAL'],[-.10,.03001,'NEUTRAL'],[.099,0,'NEUTRAL']])test('frozen threshold '+m15+'/'+m5,()=>{const x=f();Object.assign(x.input.dxy,{move_15m_pct:m15,move_5m_pct:m5});assert.equal(macroFilter(x.input).bias,bias);});
test('stale/future DXY fails closed during ACTIVE without discarding immutable plan',()=>{for(const patch of [{timestamp:new Date(base).toISOString()},{available_at:Infinity},{at:Infinity},{fresh:false}]){const x=f();Object.assign(x.input.dxy,patch);assert.equal(run(x).contract.side,'NONE');assert.equal(x.state.active_signal.status,'ACTIVE');assert.equal(x.state.active_signal.entry,100);}});
test('active entry immutable and no reverse activation',()=>{const x=f(),out=run(x);assert.equal(out.contract.side,'BUY');assert.equal(out.contract.entry,100);assert.equal(x.state.active_signal.signal_id,'one');});
test('1R alone without a confirmed favorable swing does not move stop',()=>{const x=f();run(x);assert.equal(x.state.active_signal.stop_loss,98);});
function pivots(x){x.input.m5.valid.forEach(b=>{b.low=100;b.high=106;b.open=103;b.close=103;});x.input.m5.valid[2].low=99;x.input.m5.valid[6].low=101;x.input.m5.valid[5].low=102;x.input.m5.valid[7].low=102;x.input.quote.price=105;}
test('new confirmed higher low tightens SL and permits break even at 1R',()=>{const x=f();pivots(x);const original=structuredClone(x.state.active_signal);run(x);assert.ok(x.state.active_signal.stop_loss>=100);assert.equal(x.state.active_signal.initial_stop_loss,original.initial_stop_loss);assert.equal(x.state.active_signal.initial_take_profit,original.initial_take_profit);});
test('SL never widens with less protective pivot',()=>{const x=f();pivots(x);x.state.active_signal.stop_loss=102;run(x);assert.equal(x.state.active_signal.stop_loss,102);});
test('SELL confirmed lower high only tightens SL',()=>{const x=f();pivots(x);x.state.active_signal.side='SELL';x.state.active_signal.initial_stop_loss=108;x.state.active_signal.stop_loss=108;x.state.active_signal.entry=106;x.state.active_signal.take_profit=95;x.state.active_signal.initial_take_profit=95;x.input.m5.valid.forEach(b=>{b.high=104;b.low=99;b.open=102;b.close=102;});x.input.m5.valid[2].high=107;x.input.m5.valid[6].high=105;x.input.quote.price=102;run(x);assert.ok(x.state.active_signal.stop_loss<=106);});
test('ACTIVE TP cannot extend; loss of resonance may use nearer observed target',()=>{const x=f();x.result.key_levels=[{price:120,available_at:base},{price:108,available_at:base}];run(x);assert.equal(x.state.active_signal.take_profit,110);x.input.dxy.move_5m_pct=.1;x.input.dxy.move_15m_pct=.2;run(x);assert.equal(x.state.active_signal.take_profit,108);});
test('stop observation closes old signal, never activates reverse same poll',()=>{const x=f();x.input.quote.price=97;assert.equal(run(x).contract.side,'NONE');assert.equal(x.state.active_signal.status,'CLOSED');});
test('event risk suppresses active contract but retains plan',()=>{const x=f();x.input.calendar.data=[{title:'美国 FOMC',star:3,pub_time:x.input.now}];assert.equal(run(x).contract.side,'NONE');assert.equal(x.state.active_signal.status,'ACTIVE');});
const c={macro:'BEARISH',side:'SELL',entry:4289.4,stop_loss:4293.1,take_profit:4281.6};

test('first valid contract activates once with immutable initial plan; closed id never reactivates',()=>{const x=f();delete x.state.active_signal;x.decision.contract={macro:'BULLISH',side:'BUY',entry:100,stop_loss:98,take_profit:110};run(x);const original=structuredClone(x.state.active_signal);assert.equal(x.state.activated_signal_ids.length,1);run(x);assert.equal(x.state.active_signal.activated_at,original.activated_at);x.state.active_signal.status='CLOSED';assert.equal(run(x).contract.side,'NONE');assert.equal(x.state.activated_signal_ids.length,1);});
