import test from 'node:test';import assert from 'node:assert/strict';
import {loadTradingEconomics,normalizeTE,selectSymbols,teRequest} from '../data/providers/trading-economics.js';
import {macroV2} from '../engine/macroV2.js';import {macroMarketHandler} from '../services/macro-market.js';
const now=Date.UTC(2026,8,14,12,0),iso=x=>new Date(x).toISOString();
// Synthetic identifiers are fixtures, never provider discovery results.
const identities=[{Symbol:'TEST-D',Name:'Dollar Index',Country:'United States',Type:'index'},{Symbol:'TEST-2',Name:'US 2Y',Country:'United States',Type:'bond'},{Symbol:'TEST-10',Name:'US 10Y',Country:'United States',Type:'bond'}];
const id={symbol:'TEST-D',name:'Dollar Index',country:'United States',type:'index'};
const quote={Symbol:id.symbol,Name:id.name,Country:id.country,frequency:'Live',unit:'index points',Last:100,Date:iso(now)};
const history=Array.from({length:18},(_,i)=>({Symbol:id.symbol,Date:iso(now-(18-i)*60000),Open:99,High:100,Low:98,Close:99}));
function facts(sign=1){return Object.fromEntries(['DXY','US2Y','US10Y'].map(k=>[k,{provider:'TEST_ONLY',verified:true,execution_eligible:true,value:100,at:now,available_at:now,reference_5m:100-sign,reference_15m:100-2*sign,reference_5m_at:now-300000,reference_15m_at:now-900000}]));}
test('all three rise is bearish -100 with strong confirmation',()=>{const x=macroV2(facts(),now);assert.equal(x.bias,'BEARISH');assert.equal(x.score,-100);assert.equal(x.strong,true);});
test('all three fall is bullish +100',()=>assert.equal(macroV2(facts(-1),now).bias,'BULLISH'));
test('mixed components use deterministic 40/35/25 weights',()=>{const f=facts();f.US10Y=facts(-1).US10Y;const x=macroV2(f,now);assert.equal(x.score,-50);assert.equal(x.strong,false);assert.deepEqual(x,macroV2(f,now));});
test('stale and missing critical macro force neutral with partial quality',()=>{const f=facts();f.DXY.at-=180000;let x=macroV2(f,now);assert.equal(x.quality,'PARTIAL');assert.equal(x.bias,'NEUTRAL');delete f.DXY;assert.equal(macroV2(f,now).acceptable,false);});
test('absolute yield alone cannot produce direction',()=>{const f=facts();for(const v of Object.values(f)){v.value=4.6;delete v.reference_5m;delete v.reference_15m;}const x=macroV2(f,now);assert.equal(x.score,0);assert.equal(x.bias,'NEUTRAL');});
test('yield percent differences become basis points',()=>{const f=facts();f.US2Y.value=4.6;f.US2Y.reference_5m=4.59;f.US2Y.reference_15m=4.58;const x=macroV2(f,now).components.US2Y;assert.ok(Math.abs(x.move_5m_bp-1)<1e-10);assert.ok(Math.abs(x.move_15m_bp-2)<1e-10);});
test('opposing 5m vetoes component; flat 5m does not require perfect synchronization',()=>{let f=facts();f.DXY.reference_5m=101;assert.equal(macroV2(f,now).components.DXY.signal,0);f=facts();f.US2Y.reference_5m=100;assert.equal(macroV2(f,now).strong,true);});
test('discovery uses returned symbols and rejects ambiguity',()=>{assert.equal(selectSymbols(identities).US2Y.symbol,'TEST-2');assert.throws(()=>selectSymbols([...identities,{...identities[0],Symbol:'OTHER'}]));assert.throws(()=>selectSymbols([]));});
test('quote plus complete 1m history validates both change horizons',()=>{const x=normalizeTE(quote,history,id,'DXY',now);assert.equal(x.validation.verified,true);assert.equal(x.fact.reference_15m_at,now-900000);assert.equal(x.snapshot.timestamp,iso(now));});
test('delayed quotes and wrong units or identity never eligible',()=>{for(const patch of [{frequency:'Delayed'},{unit:'USD'},{Symbol:'WRONG'},{Date:iso(now-180000)}])assert.equal(normalizeTE({...quote,...patch},history,id,'DXY',now).fact.execution_eligible,false);});
test('gaps and duplicate history reject validation; future bars excluded',()=>{const g=history.slice();g.splice(8,1);assert.equal(normalizeTE(quote,g,id,'DXY',now).validation.verified,false);assert.equal(normalizeTE(quote,[...history,history[5]],id,'DXY',now).validation.verified,false);const a=normalizeTE(quote,history,id,'DXY',now);const b=normalizeTE(quote,[...history,{...history[0],Date:iso(now+60000),Close:999}],id,'DXY',now);assert.deepEqual(a,b);});
test('missing credentials cause zero outgoing requests',async()=>{let calls=0;const x=await loadTradingEconomics({apiKey:'',fetcher:async()=>{calls++;}});assert.equal(calls,0);assert.equal(x.status,'TE_CREDENTIAL_REQUIRED');assert.equal(x.snapshot.us2y.fresh,false);});
test('credentials stay in header and provider errors are redacted',async()=>{await assert.rejects(teRequest('/markets/search/test',{apiKey:'SECRET_FIXTURE',fetcher:async(url,options)=>{assert.ok(!url.includes('SECRET_FIXTURE'));assert.equal(options.headers.Authorization,'SECRET_FIXTURE');throw Error('SECRET_FIXTURE');}}),e=>e.message==='TE_REQUEST_OR_ENTITLEMENT_FAILED');});
test('full provider uses discovered codes for identity quote and intraday calls',async()=>{const calls=[];const x=await loadTradingEconomics({apiKey:'SECRET_FIXTURE',now,fetcher:async url=>{calls.push(url);const u=new URL(url);if(u.pathname.includes('/search/'))return {ok:true,json:async()=>identities};const symbol=decodeURIComponent(u.pathname.split('/').at(-1)),r=identities.find(x=>x.Symbol===symbol);assert.ok(r);const rows=u.pathname.includes('/symbology/')?[r]:u.pathname.includes('/intraday/')?history.map(b=>({...b,Symbol:symbol})): [{...r,Date:iso(now),Last:r.Type==='bond'?4:100,unit:r.Type==='bond'?'%':'index points',frequency:'Live'}];return {ok:true,json:async()=>rows};}});assert.equal(x.status,'VERIFIED');assert.equal(Object.keys(x.facts).length,3);assert.ok(calls.some(x=>x.includes('agr=1m')));assert.ok(!JSON.stringify(x).includes('SECRET_FIXTURE'));});
test('debug returns only normalized market values; no secrets on failure',async()=>{const res={setHeader(){},status(x){this.code=x;return this;},json(x){this.body=x;return this;}};await macroMarketHandler({loader:()=>loadTradingEconomics({apiKey:''})})({method:'GET'},res);assert.deepEqual(Object.keys(res.body),['dxy','us2y','us10y']);await macroMarketHandler({loader:async()=>{throw Error('SECRET_FIXTURE');}})({method:'GET'},res);assert.equal(res.code,503);assert.ok(!JSON.stringify(res.body).includes('SECRET_FIXTURE'));});
