import test from 'node:test';import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {createHash,createHmac} from 'node:crypto';
import {signal} from '../services/signal.js';import {appendTransition} from '../services/transitions.js';import {watchHandler,signedRequest} from '../services/watch.js';import {eventsHandler} from '../services/events.js';import {RedisStore} from '../state/store.js';import {freshState} from '../engine/stateMachine.js';
const M=300000,base=Date.UTC(2026,0,1);
const bar=(i,o,h,l,c)=>({at:base+i*M,end:base+(i+1)*M,open:o,high:h,low:l,close:c,tf:'M5'});
function database(){let raw=null;return ()=>new RedisStore('https://redis.test','fixture',{fetcher:async(u,o)=>{const c=JSON.parse(o.body);let result;if(c[0]==='GET')result=raw;else if(c[0]==='EVAL'){result=(raw??'')===c[4]?1:0;if(result)raw=c[5];}return {ok:true,json:async()=>({result})};}});}
function input(rows,price,now=rows.at(-1).end+1){return {now,quote:{at:now,price,fresh:true,day_open:99,day_high:130,day_low:98},m5:{valid:rows,quality:'GOOD',flags:[]},m15:{valid:[],quality:'MISSING',flags:[]},calendar:{ok:true,data:[]},flashes:[{ok:true,data:[]}],source_errors:[]};}
const quiet=()=>{};
function run(repository,x){return signal({repository,loader:async()=>structuredClone(x),now:x.now,logger:quiet,requireDurable:true});}
const v=[bar(-1,110,111,108,110),...[[110,112,107,109],[109,110,105,106],[107,111,106,108],[108,108.1,106.4,106.5],[106.5,106.6,104.4,104.5],[104.5,104.6,101.4,101.5],[101.5,107,100,106]].map((r,i)=>bar(i,...r))];
async function ready(){const factory=database(),repo=factory();await run(repo,input(v,106));const rows=[...v,bar(7,106,112.4,105.5,111.5)];assert.equal((await run(repo,input(rows,111.5))).stage,'ARMED');rows.push(bar(8,111.5,111.8,110.8,111.1));assert.equal((await run(repo,input(rows,111.1))).stage,'SIGNAL_READY');return {factory,repo,rows};}
test('minute calls deduplicate PREPARE and advance to ARMED through existing detector',async()=>{const repo=database()();const rows=[bar(0,100,101,99,100)];const first=input(rows,100);assert.equal((await run(repo,first)).stage,'PREPARE');for(let i=1;i<4;i++)await run(repo,input(rows,100,first.now+i*60000));assert.equal(JSON.parse(await repo.read()).transitions.length,1);
 const s=freshState();s.bootstrap=false;s.bars=v.slice(0,-1);s.watermark=s.bars.at(-1).end;s.latest_result={stage:'PREPARE',signal_id:null};s.transitions=[{new_stage:'PREPARE',signal_id:null}];const raw=await repo.read();await repo.compareAndSet(raw,JSON.stringify(s));await run(repo,input(v,106));assert.equal(JSON.parse(await repo.read()).transitions.at(-1).new_stage,'ARMED');});
test('ARMED to SIGNAL_READY is persisted; cold client and minute polls do not duplicate ready',async()=>{const {factory,repo,rows}=await ready();let state=JSON.parse(await repo.read());const count=state.transitions.length;const x=await run(factory(),input(rows,111.1,rows.at(-1).end+60001));assert.equal(x.stage,'SIGNAL_READY');assert.equal(x.order_executed,false);state=JSON.parse(await factory().read());assert.equal(state.transitions.length,count);assert.ok(state.transitions.at(-1).latency_ms>=0);});
test('SIGNAL_READY to MISSED uses two-dollar no-chase threshold',async()=>{const {repo,rows}=await ready();const raw=await repo.read(),state=JSON.parse(raw);state.candidate.plan.tp1=120;state.candidate.plan.tp2=130;await repo.compareAndSet(raw,JSON.stringify(state));const x=await run(repo,input(rows,114,rows.at(-1).end+60001));assert.equal(x.stage,'MISSED');assert.equal(x.action,'NO_TRADE');assert.equal(JSON.parse(await repo.read()).transitions.at(-1).previous_stage,'SIGNAL_READY');});
test('SIGNAL_READY to INVALIDATED on structural breach',async()=>{const {repo,rows}=await ready();const x=await run(repo,input(rows,99,rows.at(-1).end+60001));assert.equal(x.stage,'INVALIDATED');assert.equal(x.action,'NO_TRADE');});
test('stale quote freezes watermark and candidate; degraded event is persisted once',async()=>{const {repo,rows}=await ready(),before=JSON.parse(await repo.read());const x=input([...rows,bar(9,111,114,110,113)],113);x.quote.fresh=false;const y=await run(repo,x);assert.equal(y.stage,'DEGRADED');assert.equal(y.action,'NO_TRADE');const after=JSON.parse(await repo.read());assert.equal(after.watermark,before.watermark);assert.deepEqual(after.candidate,before.candidate);await run(repo,{...x,now:x.now+60000});assert.equal(JSON.parse(await repo.read()).transitions.length,after.transitions.length);});
test('concurrent requests CAS-commit one transition and preserve 200 events across a fresh client',async()=>{const factory=database(),repo=factory(),x=input([bar(0,100,101,99,100)],100);await Promise.all([run(repo,x),run(factory(),x)]);assert.equal(JSON.parse(await repo.read()).transitions.length,1);let state=JSON.parse(await repo.read());for(let i=0;i<220;i++){const before=structuredClone(state);appendTransition(state,before,{stage:i%2?'ARMED':'PREPARE',signal_id:'fixture',time:String(i),action:'OBSERVE',data_quality:{}},1);}const raw=await repo.read();await repo.compareAndSet(raw,JSON.stringify(state));assert.equal(JSON.parse(await factory().read()).transitions.length,200);});
function response(){return {setHeader(){},status(n){this.code=n;return this;},json(x){this.body=x;return this;}};}
test('events returns recent-first limit; invalid limit and Redis failure are safe',async()=>{const {repo}=await ready();const h=eventsHandler({repository:repo});let r=response();await h({method:'GET',url:'/api/events/xauusd?limit=1'},r);assert.equal(r.body.events.length,1);assert.equal(r.body.events[0].new_stage,'SIGNAL_READY');r=response();await h({method:'GET',url:'/api/events/xauusd?limit=201'},r);assert.equal(r.code,400);});
const url='https://preview.test/api/watch/xauusd',key='current-test-signing-key',next='next-test-signing-key',env={QSTASH_CURRENT_SIGNING_KEY:key,QSTASH_NEXT_SIGNING_KEY:next,WATCH_DESTINATION_URL:url};
function jwt(body,signing=key,sub=url,expired=false){const n=Math.floor(Date.now()/1000),head=Buffer.from(JSON.stringify({alg:'HS256'})).toString('base64url'),payload=Buffer.from(JSON.stringify({iss:'Upstash',sub,nbf:n-1,exp:expired?n-1:n+60,body:createHash('sha256').update(body).digest('base64url')})).toString('base64url');const text=head+'.'+payload;return text+'.'+createHmac('sha256',signing).update(text).digest('base64url');}
function request(body,signature){const r=Readable.from([Buffer.from(body)]);r.method='POST';r.headers={'upstash-signature':signature};return r;}
test('official Receiver verifies both signing keys and rejects anonymous/tampered/expired/wrong URL signatures',async()=>{for(const k of [key,next])assert.equal(await signedRequest(request('{}',jwt('{}',k)),env),true);for(const r of [request('{}',undefined),request('{ }',jwt('{}')),request('{}',jwt('{}',key,'https://wrong.test')),request('{}',jwt('{}',key,url,true))])assert.equal(await signedRequest(r,env),false);});
test('watch requires authentication, never executes orders, and Redis error returns degraded without secret',async()=>{let calls=0;const h=watchHandler({verify:r=>signedRequest(r,env),run:async()=>{calls++;return {stage:'PREPARE',action:'OBSERVE'};},logger:quiet});let r=response();await h(request('{}',undefined),r);assert.equal(r.code,401);assert.equal(calls,0);r=response();await h(request('{}',jwt('{}')),r);assert.equal(calls,1);assert.equal(r.body.order_executed,false);r=response();await watchHandler({verify:async()=>true,run:async()=>{throw Error('private-token')},logger:quiet})({method:'POST'},r);assert.equal(r.code,503);assert.equal(r.body.stage,'DEGRADED');assert.ok(!JSON.stringify(r.body).includes('private-token'));});

test('sampled TP1 and TP2 remain observations, never fills',async()=>{const {repo,rows}=await ready();const s=JSON.parse(await repo.read()),p=s.candidate.plan;let x=await run(repo,input(rows,p.tp1,rows.at(-1).end+60001));assert.equal(x.stage,'TP1');assert.equal(x.order_executed,false);x=await run(repo,input(rows,p.tp2,rows.at(-1).end+120001));assert.equal(x.stage,'TP2');assert.equal(x.order_executed,false);});

test('five unchanged watcher polls advance durable revisions without duplicate transitions',async()=>{const factory=database(),repo=factory(),x=input([bar(0,100,101,99,100)],100);const versions=[];for(let i=0;i<5;i++){const r=await run(factory(),x);versions.push(r.debug.persistence.state_version);}assert.deepEqual(versions,[1,2,3,4,5]);const s=JSON.parse(await repo.read());assert.equal(s.transitions.length,1);assert.equal(s.last_watch.state_version,5);assert.equal(s.last_watch.stage,'PREPARE');});
test('user-approved Preview destination works without overriding injected signing keys',async()=>{const {PREVIEW_WATCH_URL}=await import('../config/watch.js');const keys={QSTASH_CURRENT_SIGNING_KEY:key,QSTASH_NEXT_SIGNING_KEY:next};assert.equal(await signedRequest(request('{}',jwt('{}',key,PREVIEW_WATCH_URL)),keys),true);assert.equal(await signedRequest(request('{}',jwt('{}',key,url)),keys),false);assert.deepEqual(keys,{QSTASH_CURRENT_SIGNING_KEY:key,QSTASH_NEXT_SIGNING_KEY:next});});
